In [9]:
import xarray as xr
from benchmark.bm.ensemble_score import get_ranks, get_ranks_distributions, get_entropy_of_distributions
import matplotlib.pyplot as plt
import numpy as np

In [6]:
ds_id = "278771"
# model_id_1 = "DC855F"
model_id_2 = "542704"
model_id_3 = "011A3B"

targets_3 = xr.load_dataset(f"/data/compoundx/WeatherDiff/model_output/{ds_id}/{model_id_3}_target.nc")

predictions_3 = xr.load_dataset(f"/data/compoundx/WeatherDiff/model_output/{ds_id}/{model_id_3}_gen.nc")

In [7]:
r = get_ranks_distributions(targets_3.isel({"lat":0, "lon":0, "lead_time":0}), predictions_3.isel({"lat":0, "lon":0, "lead_time":0}))

In [10]:
get_entropy_of_distributions(r)

{'z_500': array([0.96605126])}

In [16]:
len(predictions_3.ensemble_member)

2

In [27]:
for varname in predictions_3.data_vars:
    print(varname)

z_500


In [31]:
unique_values, counts = np.unique(r.z_500.values, return_counts=True)

In [32]:
unique_values

array([1, 2, 3])

In [33]:
a = np.array([1,2,4])

In [43]:
counts

array([1203,  329, 1372])

In [42]:
counts[]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [58]:
m = np.array([np.where(unique_values==a) for a in np.array([1,2,3])])

In [60]:
np.where(unique_values==a)

(array([0, 1]),)

In [56]:
counts[m]

array([[1203],
       [ 329],
       [1372]])